baasflow:
    events:
        disabled: false
        kafka:
            msk: true
            brokers: "<override from environment specific configuration>"
            connection-timeout-ms: 1000
            request-timeout-ms: 1000
            retries-count: 3
            retry-backoff-ms: 100
            glue-aws-region: "eu-central-1"
            glue-registry-name: "baasflow-dev"
            glue-schema-name: "BinXLogEvents"
            local-schema-registry-endpoint: "localhost:8081"
        channels:
            audit:
                topic: "auditlog"
            generic:
                topic: "genericlog"
