baasflow:
    events:
        audit:
            kafka:
                brokers: "localhost:9092"
                topic: auditlog
        generic:
            kafka:
                brokers: "localhost:9092"
                topic: events
