baasflow:
    events:
        audit:
            kafka:
                brokers: <override from environment specific configuration>
                topic: <override from environment specific configuration>
        generic:
            kafka:
                brokers: <override from environment specific configuration>
                topic: <override from environment specific configuration>
